---
particlefilter:
  train_script: './train.py'
  train_args:
    data_args:
      region_name: 'particlefilter'
      train_test_dataset: '/scratch/mzu/zanef2/surrogates/training_data/particlefilter_128x128_13000.h5'
    early_stop_args:
      patience: 10
      min_delta_percent: 3
  bayesian_opt_driver_args:
    architecture_config:
      trials: 100
      parameter_constraints:
      - "maxpool_kernel_size <= conv_kernel_size"
      - "conv_stride <= conv_kernel_size"
      objectives:
      - name: average_mse
        type: minimize
      - name: inference_time
        type: minimize
      parameter_space:
      - name: conv_kernel_size
        type: range
        bounds:
        - 2
        - 14
      - name: conv_stride
        type: range
        bounds:
        - 2
        - 14
      - name: maxpool_kernel_size
        type: range
        bounds:
        - 1
        - 10
      - name: fc2_size
        type: choice
        values:
        - 0
        - 2
        - 4
        - 8
        - 16
        - 32
        - 64
        - 128
      tracking_metrics:
      - average_mse
      - inference_time
  
    hyperparameter_config:
      trials: 30
      parameter_constraints:
        - "inference_time <= 3.0"
      parameter_space:
      - name: learning_rate
        type: range
        bounds:
        - 0.0001
        -  0.01
        log_scale: true
      - name: epochs
        type: fixed
        value: 50
      - name: batch_size
        type: fixed
        value: 32
      - name: dropout
        type: fixed
        value: 0
      - name: weight_decay
        type: range
        bounds:
        - 0.0001
        - 0.1
        log_scale: true
      objectives:
      - name: average_mse
        type: minimize
      tracking_metrics:
      - average_mse
miniweather:
  train_script: './train.py'
  train_args:
    data_args:
      region_name: 'MiniWeatherTimestep'
      train_test_dataset: '/scratch/mzu/zanef2/surrogates/training_data/miniweather_768_384.h5'
      train_end_index: 1000
    early_stop_args:
      patience: 3
      min_delta_percent: 10
  bayesian_opt_driver_args:
    architecture_config:
      trials: 100
      objectives:
      - name: average_mse
        type: minimize
      - name: inference_time
        type: minimize
      parameter_space:
      - name: conv1_stride
        type: fixed
        value: 1
      - name: conv1_kernel_size
        type: choice
        values:
        - 3
        - 5
        - 7
        - 9
        - 11
      - name: conv1_out_channels
        type: choice
        values:
        - 4
        - 8
        - 16
      - name: conv2_kernel_size
        type: choice
        values:
        - 0
        - 3
        - 5
        - 7
        - 9
      - name: activation_function
        type: fixed
        value: leaky_relu
      tracking_metrics:
      - average_mse
      - inference_time
    hyperparameter_config:
      trials: 15
      parameter_constraints:
        - "inference_time <= 6"
      parameter_space:
      - name: learning_rate
        type: range
        bounds:
        - 0.0001
        -  0.01
        log_scale: true
      - name: dropout
        type: range
        bounds:
        - 0.0
        - 0.5
      - name: epochs
        type: fixed
        value: 15
      - name: batch_size
        type: fixed
        value: 32
      - name: weight_decay
        type: range
        bounds:
        - 0.0001
        - 0.1
        log_scale: true
      objectives:
      - name: average_mse
        type: minimize
      tracking_metrics:
      - average_mse