---
particlefilter:
  train_script: './train.py'
  train_args:
    data_args:
      region_name: 'particlefilter'
      load_entire: false
      train_test_dataset: '/scratch/mzu/zanef2/surrogates/training_data/particlefilter_128x128_13000.h5'
    early_stop_args:
      patience: 10
      min_delta_percent: 3
  bayesian_opt_driver_args:
    architecture_config:
      trials: 100
      parameter_constraints:
      - "maxpool_kernel_size <= conv_kernel_size"
      - "conv_stride <= conv_kernel_size"
      objectives:
      - name: average_mse
        type: minimize
      - name: inference_time
        type: minimize
      parameter_space:
      - name: conv_kernel_size
        type: range
        bounds:
        - 2
        - 14
      - name: conv_stride
        type: range
        bounds:
        - 2
        - 14
      - name: maxpool_kernel_size
        type: range
        bounds:
        - 1
        - 10
      - name: fc2_size
        type: range
        bounds:
        - 0 
        - 128
      tracking_metrics:
      - average_mse
      - inference_time
  
    hyperparameter_config:
      trials: 30
      parameter_constraints:
        - "inference_time <= 3.0"
      parameter_space:
      - name: learning_rate
        type: range
        bounds:
        - 0.0001
        -  0.01
        log_scale: true
      - name: epochs
        type: fixed
        value: 50
      - name: batch_size
        type: fixed
        value: 32
      - name: dropout
        type: fixed
        value: 0
      - name: weight_decay
        type: range
        bounds:
        - 0.0001
        - 0.1
        log_scale: true
      objectives:
      - name: average_mse
        type: minimize
      tracking_metrics:
      - average_mse
miniweather:
  train_script: './train.py'
  train_args:
    data_args:
      region_name: 'MiniWeatherTimestep'
      train_test_dataset: '/scratch/mzu/zanef2/surrogates/training_data/miniweather_768_384.h5'
      load_entire: true
      train_end_index: 1000
    early_stop_args:
      patience: 3
      min_delta_percent: 10
  bayesian_opt_driver_args:
    architecture_config:
      trials: 100
      objectives:
      - name: average_mse
        type: minimize
      - name: inference_time
        type: minimize
      parameter_space:
      - name: conv1_stride
        type: fixed
        value: 1
      - name: conv1_kernel_size
        type: range
        bounds:
        - 3
        - 15 
      - name: conv1_out_channels
        type: range
        bounds:
        - 4
        - 48
      - name: conv2_kernel_size
        type: range
        bounds:
        - 0
        - 16
      - name: activation_function
        type: fixed
        value: leaky_relu
      tracking_metrics:
      - average_mse
      - inference_time
    hyperparameter_config:
      trials: 15
      parameter_constraints:
        - "inference_time <= 2000"
      parameter_space:
      - name: learning_rate
        type: range
        bounds:
        - 0.0001
        -  0.01
        log_scale: true
      - name: dropout
        type: range
        bounds:
        - 0.0
        - 0.5
      - name: epochs
        type: fixed
        value: 10
      - name: batch_size
        type: fixed
        value: 32
      - name: weight_decay
        type: range
        bounds:
        - 0.0001
        - 0.1
        log_scale: true
      objectives:
      - name: average_mse
        type: minimize
      tracking_metrics:
      - average_mse
binomial_options:
  train_script: './train.py'
  train_args:
    data_args:
      region_name: 'BinomialOptionsKernel'
      train_test_dataset: '/scratch/mzu/zanef2/surrogates/training_data/binomial_options_16777216.h5'
      load_entire: true
      train_end_index: 6194304 
      # We have so much data for this one,
      # performance is affected a lot by 
      # the amount of test data
      test_split: 0.97
      max_test_batches: 8000
    early_stop_args:
      patience: 5
      min_delta_percent: 10
  bayesian_opt_driver_args:
    architecture_config:
      trials: 100
      parameter_constraints:
      - "hidden2_features <= hidden1_features"
      objectives:
      - name: average_mse
        type: minimize
      - name: inference_time
        type: minimize
      parameter_space:
      - name: multiplier
        type: range
        bounds: 
        - 1
        - 32
      - name: hidden1_features
        type: range
        bounds:
        - 5
        - 32
      - name: hidden2_features
        type: range
        bounds:
        - 0
        - 32
      tracking_metrics:
      - average_mse
      - inference_time
    hyperparameter_config:
      trials: 30
      parameter_constraints:
        - "inference_time <= 4"
      parameter_space:
      - name: learning_rate
        type: range
        bounds:
        - 0.0001
        -  0.01
        log_scale: true
      - name: epochs
        type: fixed
        value: 50
      - name: batch_size
        type: fixed
        value: 32
      - name: dropout
        type: range
        bounds:
        - 0.0
        - 0.1
      - name: weight_decay
        type: range
        bounds:
        - 0.0001
        - 0.1
        log_scale: true
      objectives:
      - name: average_mse
        type: minimize
      tracking_metrics:
      - average_mse
bonds:
  train_script: './train.py'
  train_args:
    data_args:
      region_name: 'BondsKernel'
      train_test_dataset: '/scratch/mzu/zanef2/surrogates/training_data/bonds_16777216.h5'
      load_entire: true
      train_end_index: 6194304 
      # We have so much data for this one,
      # performance is affected a lot by 
      # the amount of test data
      test_split: 0.95
      # Admittedly, this is awkward.
      # We don't want to use our entire 'test set'
      # (non training set) for validation, but we
      # do want to use the entire thing for measuring
      # inference tim
      max_test_batches: 8000
    early_stop_args:
      patience: 5
      min_delta_percent: 10
  bayesian_opt_driver_args:
    architecture_config:
      trials: 100
      parameter_constraints:
      - "hidden2_features <= hidden1_features"
      objectives:
      - name: average_mse
        type: minimize
      - name: inference_time
        type: minimize
      parameter_space:
      - name: multiplier
        type: range
        bounds: 
        - 1
        - 32
      - name: hidden1_features
        type: range
        bounds:
        - 5
        - 32
      - name: hidden2_features
        type: range
        bounds:
        - 0
        - 32
      tracking_metrics:
      - average_mse
      - inference_time
    hyperparameter_config:
      trials: 30
      parameter_constraints:
        - "inference_time <= 8"
      parameter_space:
      - name: learning_rate
        type: range
        bounds:
        - 0.0001
        -  0.01
        log_scale: true
      - name: epochs
        type: fixed
        value: 50
      - name: batch_size
        type: fixed
        value: 32
      - name: dropout
        type: range
        bounds:
        - 0.0
        - 0.1
      - name: weight_decay
        type: range
        bounds:
        - 0.0001
        - 0.1
        log_scale: true
      objectives:
      - name: average_mse
        type: minimize
      tracking_metrics:
      - average_mse