---
particlefilter:
  train_script: './train_particlefilter.py'
  train_args:
    data_args:
      region_name: 'particlefilter'
      train_test_dataset: '/scratch/mzu/zanef2/particlefilter_128x128_6500.h5'
  bayesian_opt_driver_args:
    architecture_config:
      trials: 100
      parameter_constraints:
      - "maxpool_kernel_size <= conv_kernel_size"
      - "conv_stride <= conv_kernel_size"
      objectives:
      - name: total_mse
        type: minimize
      - name: inference_time
        type: minimize
      parameter_space:
      - name: conv_kernel_size
        type: range
        bounds:
        - 3
        - 10
      - name: conv_stride
        type: range
        bounds:
        - 3
        - 10
      - name: maxpool_kernel_size
        type: range
        bounds:
        - 1
        - 10
      tracking_metrics:
      - total_mse
      - inference_time
  
    hyperparameter_config:
      trials: 30
      parameter_constraints:
        - "inference_time <= 3.0"
      parameter_space:
      - name: learning_rate
        type: range
        bounds:
        - 0.0001
        -  0.01
        log_scale: true
      - name: epochs
        type: fixed
        value: 50
      - name: batch_size
        type: fixed
        value: 32
      - name: dropout
        type: fixed
        value: 0
      - name: weight_decay
        type: range
        bounds:
        - 0.0001
        - 0.1
        log_scale: true
      objectives:
      - name: total_mse
        type: minimize
      tracking_metrics:
      - total_mse