---
particlefilter:
  models_directory: '/scratch/mzu/zanef2/surrogates/hpacml-experimentation/2024-03-05_particlefilter/models'
  benchmark_location: '/scratch/mzu/zanef2/surrogates/SurrogateBenchmarks/benchmarks/particlefilter-cuda/'
  all_trials_file: '/scratch/mzu/zanef2/surrogates/hpacml-experimentation/2024-03-05_particlefilter/trial_results.csv'
  run_command: './main -x 128 -y 128 -z 24 -np $((1<<12))'
  # TODO: This will go away and we use Parsl to run the benchmarks for every surrogate in the directory
  surrogate_model: '/scratch/mzu/zanef2/surrogates/hpacml-experimentation/2024-03-05_particlefilter/models/model_13_4.pth'
  # We run the benchmark in exact mode to compare against the approx outputs
  comparison_args:
    region_name: 'particlefilter'
    loss_fn: rmse
miniweather:
  train_args:
    pareto_frontier_file: '/scratch/mzu/zanef2/surrogates/hpacml-experimentation/2024-02-28_miniweather/pareto_parameters.json'
    all_trials_file: '/scratch/mzu/zanef2/surrogates/hpacml-experimentation/2024-02-28_miniweather/trial_results.csv'
    pareto_only: false
    epochs: 500
    early_stop_args:
      patience: 100
      min_delta_percent: 1
  data_args:
    region_name: 'MiniWeatherTimestep'
    load_entire: false
    train_test_dataset: '/scratch/mzu/zanef2/surrogates/training_data/miniweather_768_384.h5'
    output_models_directory: 'miniweather_output_models'
minibude:
  models_directory: '/scratch/mzu/zanef2/surrogates/hpacml-experimentation/2024-03-05_minibude/models'
  run_command: './main -x 128 -y 128 -z 24 -np $((1<<12))'
  surrogate_model: '/scratch/mzu/zanef2/surrogates/hpacml-experimentation/2024-03-05_minibude/models/model_2_18.pth'
  all_trials_file: '/scratch/mzu/zanef2/surrogates/hpacml-experimentation/2024-03-05_minibude/trial_results.csv'
  benchmark_location: '/scratch/mzu/zanef2/surrogates/SurrogateBenchmarks/benchmarks/miniBUDE_testing/'
  dataset_gen_command:
  - './bude'
  - '--deck'
  - '/scratch/mzu/zanef2/miniBUDE_data/bm2'
  - '-i'
  - '1'
  - '-n'
  - '2097152'
  # We run the benchmark in exact mode to compare against the approx outputs
  comparison_args:
    region_name: 'BUDEOutput'
    start_index: 1048576
    loss_fn: mape
